/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TestPlatform;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.sound.sampled.AudioFormat;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.DataLine;
import javax.sound.sampled.SourceDataLine;
import javax.sound.sampled.TargetDataLine;

/**
 *
 * @author 18293468
 */
public class captureTest extends javax.swing.JFrame {
    
    boolean stopCapture = false;
    ByteArrayOutputStream baos;
    AudioFormat audioFormat;
    TargetDataLine tdl;
    AudioInputStream ais;
    SourceDataLine sourceDataLine;
    
    // TODO look at Javax.sound library    
    
    /**
     * Creates new form TestPlatform
     */
    public captureTest() {
        initComponents();
        
        playBtn.setEnabled(false);
        recordBtn.setEnabled(true);
        stopBtn.setEnabled(false);
        
    }
    
    private void recordAudio(){
        try{
            audioFormat = getAudioFormat();
            DataLine.Info dli = new DataLine.Info(TargetDataLine.class, audioFormat);
            tdl = (TargetDataLine) AudioSystem.getLine(dli);
            tdl.open(audioFormat);
            tdl.start();
            Thread captureThread = new Thread(new CaptureThread());
            captureThread.start();
            
        } catch(Exception E){
            System.out.println(E);
            System.exit(0);
        }
    }
    
    private void playAudio(){
        try{
            byte audioData[] = baos.toByteArray();
            InputStream bais = new ByteArrayInputStream(audioData);
            AudioFormat audioFormat = getAudioFormat();
            ais = new AudioInputStream(bais, audioFormat, audioData.length/audioFormat.getFrameSize());
            DataLine.Info dataLineInfo = new DataLine.Info(SourceDataLine.class, audioFormat);
            sourceDataLine = (SourceDataLine) AudioSystem.getLine(dataLineInfo);
            sourceDataLine.open();
            sourceDataLine.start();
            
            Thread playThread = new Thread(new PlayThread());
            playThread.start();
        } catch(Exception E){
            System.out.println(E);
            System.exit(0);
        }
    }
    
    private AudioFormat getAudioFormat(){
        float sampleRate = 44000.0F;
        int sampleSizeIntBits = 16;
        int channels = 1;
        boolean signed = true;
        boolean bigEndian = false;
        
        //create and send audio format
        return new AudioFormat(sampleRate, sampleSizeIntBits, channels, signed, bigEndian);
    }
    
    //create two thread classes
    class CaptureThread extends Thread {
        byte tempBuffer[] = new byte[10000];
        public void run(){
            baos = new ByteArrayOutputStream();
            stopCapture = false;
             int count;
            try{
                while(!stopCapture){
                    count = tdl.read(tempBuffer, 0, tempBuffer.length);
                    if(count > 0){
                        baos.write(tempBuffer, 0, count);
                    }
                }
                
                baos.close();
            } catch(Exception E) {
                
            }
                
        }
    }
    
    class PlayThread extends Thread{
        byte tempBuffer[] = new byte[10000];
        public void run(){
            try{
                int count;
                while((count = ais.read(tempBuffer, 0, tempBuffer.length)) != -1){
                    if(count > 0){
                        sourceDataLine.write(tempBuffer, 0, tempBuffer.length);
                    }
                }
                
                sourceDataLine.drain();
                sourceDataLine.close();
            } catch (Exception E) {
                System.out.println(E);
                System.exit(0);
            }
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        playBtn = new javax.swing.JButton();
        recordBtn = new javax.swing.JButton();
        stopBtn = new javax.swing.JButton();
        testSC_Label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        playBtn.setText("Play");
        playBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playBtnActionPerformed(evt);
            }
        });

        recordBtn.setText("Record");
        recordBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recordBtnActionPerformed(evt);
            }
        });

        stopBtn.setText("Stop");
        stopBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stopBtnActionPerformed(evt);
            }
        });

        testSC_Label.setText("testing sound capture");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(testSC_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(playBtn)
                        .addGap(42, 42, 42)
                        .addComponent(recordBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(stopBtn)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(testSC_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(playBtn)
                    .addComponent(recordBtn)
                    .addComponent(stopBtn))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void playBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playBtnActionPerformed
        playAudio();
    }//GEN-LAST:event_playBtnActionPerformed

    private void recordBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recordBtnActionPerformed
        playBtn.setEnabled(false);
        recordBtn.setEnabled(false);
        stopBtn.setEnabled(true);
        recordAudio();
    }//GEN-LAST:event_recordBtnActionPerformed

    private void stopBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stopBtnActionPerformed
        playBtn.setEnabled(true);
        recordBtn.setEnabled(true);
        stopBtn.setEnabled(false);
        stopCapture = true;
    }//GEN-LAST:event_stopBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(captureTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(captureTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(captureTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(captureTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {        
                new captureTest().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton playBtn;
    private javax.swing.JButton recordBtn;
    private javax.swing.JButton stopBtn;
    private javax.swing.JLabel testSC_Label;
    // End of variables declaration//GEN-END:variables
}
